routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('ticket','TicketsController');
Route::resource('ticketreply','TicketsReplyController');
Route::resource('customer','CustomersController');
Route::resource('users','UsersController');

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    //
    protected $fillable = [
        'referenceNo',
        'cusName',
        'email',
        'phone',
        'problem',
        'reply',
        'status'
            
    ];

    public function ticketsReply(){
        return $this->belongTo('App/TicketReply');
    }

    public function customers(){
        return $this->belongTo('App/Customer');
    }

    public function users(){
        return $this->belongTo('App/User');
    }
}

app/Http/Controllers/TicketsController.php
<?php

namespace App\Http\Controllers;

use App\Ticket;
use Illuminate\Http\Request;

use App\Mail\ReplyMail;
use Illuminate\Support\Facades\Mail;

use Illuminate\Support\Facades\Auth;

class TicketsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if(Auth::check()){
        $ticket = Ticket::paginate(2);

        return view('ticket.index',['tickets'=>$ticket]);

    }
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('ticket.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $ticket = Ticket::create([
            'cusName' => $request->input('cusname'),
            'email' => $request->input('email'),
            'phone' => $request->input('phone'),
            'referenceNo' =>$request->input('ref'),
            'problem' =>$request->input('problem'),
            'status' =>$request->input('status')
            
            

        ]);

        $refNo = $request->input('ref');

        Mail::to($ticket->email)->send(new TicketMail($refNo));

        if($ticket){
            return redirect()->route('ticket.create')->with('sucess','Successfully Send the Ticket');
        }

        return back()->withInput()->with('errors','Error Adding new ticket');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {
        //
        $ticket = Ticket::find($ticket->id);

        return view('ticket.show',['ticket'=>$ticket]);
    }


    public function refshow(Ticket $ticket)
    {
        //
        $ticket = Ticket::find($ticket->referenceNo);

        return view('ticket.refshow',['ticket'=>$ticket]);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit(Ticket $ticket)
    {
        //
        $ticket = Ticket::find($ticket->id);

        return view('ticket.edit',['ticket'=>$ticket]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ticket $ticket)
    {
        //

        $ticketUpdate = Ticket::where('id', $ticket->id)
            ->update([
                'reply'=>$request->input('reply'),
                'status'=>$request->input('status')              

            ]); 
            

            $reply = $request->input('reply');
            Mail::to($ticket->email)->send(new ReplyMail($reply));
           

        if($ticketUpdate){
            return redirect()->route('ticket.show',['ticket'=> $ticket->id])
            ->with('sucess','Successfully Send the reply');
        }

        

        return back()->withInput();

        
        
        

    }

    

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {
        //
    }
}

resources/views/ticket/create.blade.php
@extends('layouts/app')

@section('content')

<div class="container mt-5">
    <center><h2>Ticket Details</h2></center>
    <form method="post" action={{ route('ticket.store') }}">
        {{ csrf_field()}}

    

  <div class="form-group">
    <label for="exampleInputEmail1">Reference Number</label>
    <input class="form-control" type="text" id="ref" name="ref" >
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Customer Name</label>
    <input class="form-control" type="text" id="cusname" name="cusname">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">E-mail</label>
    <input class="form-control" type="text" id="email" name="email">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Phone</label>
    <input class="form-control" type="text" id="phone" name="phone">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Problem</label>
    <textarea class="form-control" id="problem" name="problem"></textarea>
  </div>
  
  <input type="hidden" name="status" value="New">
  <input type="hidden" name="ref" value="{{str_random(10)}}">
  <button type="submit" class="btn btn-primary">Send</button>
</form>
    </div>


@endsection

resources/views/ticket/edit.blade.php
@extends('layouts/app')

@section('content')

<div class="container mt-5">
    <center><h2>Ticket Details</h2></center>
    <form method="post" action={{ route('ticket.update',[$ticket->id]) }}">
        {{ csrf_field()}}

    <input type="hidden" name="_method" value="put">

    

  <div class="form-group">
    <label for="exampleInputEmail1">Reference Number</label>
    <input class="form-control" type="text" id="ref" name="ref" value="{{$ticket->referenceNo}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Customer Name</label>
    <input class="form-control" type="text" id="cusname" name="cusname" value="{{$ticket->cusName}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">E-mail</label>
    <input class="form-control" type="text" id="email" name="email" value="{{$ticket->email}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Phone</label>
    <input class="form-control" type="text" id="phone" name="phone" value="{{$ticket->phone}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Problem</label>
    <textarea class="form-control" id="problem" name="problem" readonly>{{$ticket->problem}}</textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Reply</label>
    <textarea class="form-control" id="reply" name="reply" required>{{$ticket->reply}}</textarea>
  </div>

  <input type="hidden" name="status" value="Viewed">
  <button type="submit" class="btn btn-primary">Edit</button>
</form>
    </div>


@endsection

resources/views/ticket/index.blade.php
@extends('layouts/app')

@section('content')

<style>
 @media (max-width: 300px) {

.test1 {
    width: 100% !important;
    float: left;
}
}
</style>


<div class="container col-md-9 col-lg-9 col-sm-3">
    <h1>Ticket List</h1>
    <br>

    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for Customer" title="Type in a name">
    </br></br>
                <table class="table table-bordered mb-5" id="myTable">
                    <thead>
                        <tr class="table-success">
                            <th scope="col" class="test1">#</th>
                            <th scope="col" class="test1">Reference No</th>
                            <th scope="col" class="test1">Customer name</th>
                            <th scope="col" class="test1">Status</th>
                            <th scope="col" class="test1">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tickets as $ticket)
                        <tr>
                            <th scope="row" class="test1">{{$ticket->id }}</th>
                            <td class="test1">{{ $ticket->referenceNo }}</td>
                            <td class="test1">{{ $ticket->cusName }}</td>
                            @if( $ticket->status == 'New' )
                            <td class="test1"><font color="red">{{ $ticket->status }}</font></td>
                            @else
                            <td class="test1">{{ $ticket->status }}</td>
                            @endif
                            <td class="test1"><a href="/ticket/{{ $ticket->id }}" ><button class='btn btn-success btn-sm'>View</button></a><a href="/ticket/{{ $ticket->id }}/edit" >&nbsp;<button class='btn btn-success btn-sm'>Reply</button></a></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $tickets->links() }}
    </div>


    <script>
function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>

                </div>

@endsection

resources/views/ticket/refshow.blade.php
@extends('layouts/app')

@section('content')

<div class="container mt-5">
    <center><h2>Ticket Details</h2></center>
    
  <div class="form-group">
    <label for="exampleInputEmail1">Reference Number</label>
    <input class="form-control" type="text" id="ref" name="ref" value="{{$ticket->referenceNo}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Customer Name</label>
    <input class="form-control" type="text" id="cusname" name="cusname" value="{{$ticket->cusName}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">E-mail</label>
    <input class="form-control" type="text" id="email" name="email" value="{{$ticket->email}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Phone</label>
    <input class="form-control" type="text" id="phone" name="phone" value="{{$ticket->phone}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Problem</label>
    <textarea class="form-control" id="problem" name="problem" readonly>{{$ticket->problem}}</textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Reply</label> 
    <textarea class="form-control" id="reply" name="reply" readonly>{{$ticket->reply}}</textarea>
  </div>
  <form action="/ticket">
  <button type="submit" class="btn btn-primary">Back</button>
  </form>

    </div>


@endsection

resources/views/ticket/show.blade.php
@extends('layouts/app')

@section('content')

<div class="container mt-5">
    <center><h2>Ticket Details</h2></center>
    
  <div class="form-group">
    <label for="exampleInputEmail1">Reference Number</label>
    <input class="form-control" type="text" id="ref" name="ref" value="{{$ticket->referenceNo}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Customer Name</label>
    <input class="form-control" type="text" id="cusname" name="cusname" value="{{$ticket->cusName}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">E-mail</label>
    <input class="form-control" type="text" id="email" name="email" value="{{$ticket->email}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Phone</label>
    <input class="form-control" type="text" id="phone" name="phone" value="{{$ticket->phone}}" readonly>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Problem</label>
    <textarea class="form-control" id="problem" name="problem" readonly>{{$ticket->problem}}</textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Reply</label>
    <textarea class="form-control" id="reply" name="reply">{{$ticket->reply}}</textarea>
  </div>
  <form action="/ticket">
  <button type="submit" class="btn btn-primary">Back</button>
  </form>

    </div>


@endsection